# Fleet configuration
######################################
outputs:
  default:
    type: elasticsearch
    hosts: 'https://elasticsearch:9200'
    username: 'elastic'
    password: ${ELASTIC_PASSWORD}
    ssl.certificate_authorities: ['/elkcerts/certs/ca/ca.crt']
    api_key: 'XzjYnnYBOiasdPnzSbxc:c9M3eWQoTSO'

inputs:
  - type: system/metrics

    # Namespace name must conform to the naming conventions for Elasticsearch indices, cannot contain dashes (-), and cannot exceed 100 bytes
    # For index naming restrictions, see https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html#indices-create-api-path-params
    data_stream.namespace: default
    use_output: default
    streams:
      - metricset: cpu
        # Dataset name must conform to the naming conventions for Elasticsearch indices, cannot contain dashes (-), and cannot exceed 100 bytes
        data_stream.dataset: system.cpu
      - metricset: memory
        data_stream.dataset: system.memory
      - metricset: network
        data_stream.dataset: system.network
      - metricset: filesystem
        data_stream.dataset: system.filesystem

fleet:
  enabled: true
  access_api_key: 'XzjYnnYBOiasdPnzSbxc:c9M3eWQoTSO'
  hosts: [ 'https://elasticsearch:5601' ]
  ssl.certificate_authorities: ["/elkcerts/certs/kibana/kibana.crt"]
  kibana:
    # kibana minimal configuration
    hosts: ["https://elasticsearch:5601"]
    protocol: "https"
    ssl.certificate_authorities: ["/elkcerts/certs/kibana/kibana.crt"]

    # optional values
    
agent.logging.to_stderr: true
#host:
#  enabled: true

