FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y wget curl

RUN wget https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.17.0-linux-x86_64.tar.gz
RUN tar xzf elastic-agent-7.17.0-linux-x86_64.tar.gz
