version: '3.9'

services:
  nginx:
    build:
      context: .
    volumes:
      - ./certs:/etc/nginx/certs/
      - ./static:/etc/nginx/staticpages/
    privileged: true
    ports:
     - "80:80"
     - "443:443"
