version: '3.9'

services:

  elastic-agent-docker:
    build:
      context: elastic-agent-docker/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION:-}
    container_name: elastic-agent-docker
    restart: always
    user: root # note, synthetic browser monitors require this set to `elastic-agent`
    environment:
      # Variables https://www.elastic.co/guide/en/fleet/current/agent-environment-variables.html
      ELASTICSEARCH_HOST: "https://elasticsearch:9200"
      ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD:-}
      ELASTICSEARCH_CA: "/elkcerts/certs/ca/ca.crt"
      KIBANA_HOST: "https://kibana:5601"
      KIBANA_USERNAME: "elastic"
      KIBANA_PASSWORD: ${ELASTIC_PASSWORD:-}
      KIBANA_CA: "/elkcerts/certs/ca/ca.crt"

      #Prepare Kibana for Fleet
      KIBANA_FLEET_SETUP: 1
      KIBANA_FLEET_HOST: "https://kibana:5601"
      KIBANA_FLEET_USERNAME: "elastic"
      KIBANA_FLEET_PASSWORD: ${ELASTIC_PASSWORD:-}
      KIBANA_FLEET_CA: "/elkcerts/certs/ca/ca.crt"

      # Bootstrap Fleet Server
      FLEET_SERVER_ENABLE: 1
      FLEET_SERVER_ELASTICSEARCH_HOST:  "https://elasticsearch:9200"
      FLEET_SERVER_ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD:-}
      FLEET_SERVER_ELASTICSEARCH_CA:  "/elkcerts/certs/ca/ca.crt"

      FLEET_SERVER_SERVICE_TOKEN: ${FLEET_SERVER_SERVICE_TOKEN:-}
      FLEET_SERVER_POLICY_NAME:  ${FLEET_SERVER_POLICY_NAME:-}
      FLEET_SERVER_POLICY_ID:  ${FLEET_SERVER_POLICY:-}
      FLEET_SERVER_POLICY:  ${FLEET_SERVER_POLICY:-}"
      FLEET_SERVER_HOST: "https://elasticsearch:8220"
      # # #FLEET_SERVER_PORT: "8220"
      FLEET_SERVER_CERT: "/elkcerts/certs/fleetserver/fleetserver.crt"
      FLEET_SERVER_CERT_KEY: "/elkcerts/certs/fleetserver/fleetserver.key"
      FLEET_SERVER_ES_CA: "/elkcerts/certs/ca/ca.crt"

      # Enroll elastic agent
      FLEET_ENROLL: 1
      FLEET_ENROLLMENT_TOKEN: ${FLEET_SERVER_SERVICE_TOKEN:-}
      FLEET_URL: "https://elasticsearch:8220"
      FLEET_CA: "/elkcerts/certs/ca/ca.crt"
      CERTIFICATE_AUTHORITIES: "/elkcerts/certs/ca/ca.crt"
      FLEET_CERT: "/elkcerts/certs/fleetserver/fleetserver.crt"
      FLEET_CERT_KEY: "/elkcerts/certs/fleetserver/fleetserver.key"

    networks:
      - elk
    depends_on:
      - elasticsearch
      - kibana
    volumes:
      - generatedcerts:/elkcerts/certs/:z
      - ./elastic-agent-docker/config/elastic-agent.yml:/usr/share/elastic-agent/elastic-agent.yml:z
      - ./elastic-agent-docker/config/fleet.yml:/usr/share/elastic-agent/fleet.yml:z

networks:
  elk:
    driver: bridge

volumes:
  generatedcerts:
