---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/master/docker/data/logstash/config/logstash-full.yml
#
http.host: "logstash"
node.name: logstash
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.elasticsearch.password: "${ELASTIC_PASSWORD}"
xpack.monitoring.elasticsearch.ssl.certificate_authority: "/elkcerts/certs/ca/ca.crt"
xpack.monitoring.elasticsearch.ssl.verification_mode: "certificate"
xpack.monitoring.elasticsearch.hosts: [ "https://elasticsearch:9200" ]